using System;
using System.Collections.Generic;
using System.Linq;

// One report in the audit: a neutral description, optional aggregate summary tables, and a
// flat list of findings (pre-sorted by the producer, most-likely-to-help first). Reports that
// are purely aggregate (count reconciliation, field hygiene) carry summary tables and no
// findings. The renderer treats both the same way.

namespace BeastieBot3.Audit.Model;

// Where a report sits in the document. IUCN-owned data first, methodology/coverage after.
internal enum AuditReportTier {
    IucnCore,
    Methodology,
}

// Coarse "kind of opportunity" used only to order and badge reports neutrally. Breaking =
// affects what the public site or API can currently serve; FixableData = a concrete value to
// tidy; Advisory = a divergence or coverage observation to consider.
internal enum BreakageClass {
    Breaking,
    FixableData,
    Advisory,
}

// A small aggregate table (counts by class, by issue kind, reconciliation, etc.).
internal sealed class AuditSummaryTable {
    public required string Title { get; init; }
    public string? Note { get; init; }
    public required IReadOnlyList<string> Headers { get; init; }
    // Per-row cell values, aligned to Headers. Numeric columns are right-aligned via NumericColumns.
    public required IReadOnlyList<IReadOnlyList<string>> Rows { get; init; }
    // Indexes of columns to right-align as numbers.
    public IReadOnlyList<int> NumericColumns { get; init; } = Array.Empty<int>();
}

internal sealed class AuditReport {
    public required string Id { get; init; }              // kebab id, also the page/file stem
    public required string Title { get; init; }
    public AuditReportTier Tier { get; init; } = AuditReportTier.IucnCore;
    public BreakageClass Breakage { get; init; } = BreakageClass.Advisory;

    // Neutral description shown at the top of the report page (one or more paragraphs of
    // plain text or the tiny markdown subset). Generated by code, release-agnostic.
    public required string Summary { get; init; }

    // Data provenance line, e.g. "IUCN Red List 2025-2 (CSV export)".
    public required string DataSourceLabel { get; init; }

    public IReadOnlyList<AuditSummaryTable> SummaryTables { get; init; } = Array.Empty<AuditSummaryTable>();

    public IReadOnlyList<AuditColumn> Columns { get; init; } = Array.Empty<AuditColumn>();

    // Findings in importance order (the producer sorts; the renderer preserves it). This is what
    // the HTML preview and full-list pages render.
    public IReadOnlyList<AuditFinding> Findings { get; init; } = Array.Empty<AuditFinding>();

    // The rows written to the CSV download. Defaults to Findings; a report may set a larger set
    // (e.g. the CoL crosscheck shows high-signal rows in HTML but keeps every row in the CSV).
    public IReadOnlyList<AuditFinding>? CsvFindings { get; init; }
    public IReadOnlyList<AuditFinding> CsvRows => CsvFindings ?? Findings;

    // Headline number for the index card. Usually Findings.Count, but aggregate reports set
    // their own (e.g. the number of fields profiled).
    public int? HeadlineCount { get; init; }

    // Ordered grouping levels for the full-list page. When the finding count is large the full list
    // splits into a tree: by the first level, then any over-sized group splits by the next, and so
    // on (e.g. class then order then family). Empty means no split.
    public IReadOnlyList<AuditGroupLevel> GroupLevels { get; init; } = Array.Empty<AuditGroupLevel>();

    // True when the report has nothing to list this release (shown as a clean "no observations").
    public bool IsEmpty => Findings.Count == 0 && SummaryTables.Count == 0;

    public int Count => HeadlineCount ?? Findings.Count;
}

internal sealed record AuditGroupLevel(string Label, Func<AuditFinding, string?> Selector);

// Common grouping ladders for full-list tree splitting.
internal static class AuditGroups {
    public static IReadOnlyList<AuditGroupLevel> ByClass => new[] {
        new AuditGroupLevel("class", f => f.Class),
    };

    public static IReadOnlyList<AuditGroupLevel> ByClassOrderFamily => new[] {
        new AuditGroupLevel("class", f => f.Class),
        new AuditGroupLevel("order", f => f.Order),
        new AuditGroupLevel("family", f => f.Family),
    };
}
