namespace BeastieBot3.Shared.SiteData;

/// The English name of each ISO 639 language code, keyed as the site database stores a common
/// name's language: the ISO 639-1 code when the language has one ("fr"), else its ISO 639-3 code
/// ("yue"), and ISO 639-5 codes for groups of languages ("phi"). The data is generated by
/// generate-language-names.mjs from the ISO 639 tables and CLDR's English names
/// (LanguageNameTable.Data.cs). site build-db keeps a common name from the Catalogue of Life,
/// Wikidata or Wikipedia only when this table has its language, and the site shows these names.
public static partial class LanguageNameTable {
    private static readonly Lazy<Dictionary<string, string>> Names = new(Load);

    /// The English name of the code (lower case, as stored), or null when the table has none.
    public static string? Name(string code) => Names.Value.GetValueOrDefault(code);

    public static bool Contains(string code) => Names.Value.ContainsKey(code);

    public static int Count => Names.Value.Count;

    private static Dictionary<string, string> Load() {
        var names = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var line in Data.Split('\n')) {
            var tab = line.IndexOf('\t');
            if (tab > 0) {
                names[line[..tab]] = line[(tab + 1)..].TrimEnd('\r');
            }
        }
        return names;
    }
}
