using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

// Turns a generated list file into the text of a user-space draft page, and builds the index page
// that links every draft. Pure: no I/O, so WikipediaPostDraftsCommand and the tests share it.
//
// A user-space page must not sit in article categories (WP:USERNOCAT), so the list's
// [[Category:...]] links move into {{Draft categories}}, which shows them as a list and applies
// them only once the page is moved to the article namespace. The text is otherwise unchanged, so a
// draft can be copied over the article as it is.

namespace BeastieBot3.Wikipedia;

internal enum DraftGroup {
    Iucn,
    Australia,
}

// A draft as it appears on the index: the article it is for and the size of the posted text.
internal sealed record DraftIndexEntry(DraftGroup Group, string ArticleTitle, string DraftTitle, int Bytes);

internal static class DraftPageBuilder {
    // $wgMaxArticleSize on English Wikipedia is 2048 KiB; a save over it fails with contenttoobig.
    public const int MaxPageBytes = 2048 * 1024;

    private static readonly Regex CategoryLink = new(@"\[\[\s*[Cc]ategory\s*:[^\[\]]*\]\]", RegexOptions.Compiled);
    private static readonly Regex IucnVersion = new(@"IUCN Red List of Threatened Species\. Version (\d{4}-\d+)", RegexOptions.Compiled);

    public static string DraftTitle(string baseTitle, string articleTitle) => $"{baseTitle}/{articleTitle}";

    public static string FormatDate(DateTime date) => date.ToString("d MMMM yyyy", CultureInfo.InvariantCulture);

    // The banner's date is the day the list file was generated, not the day it is posted, so posting
    // the same file again produces the same text and the page is skipped as unchanged.
    public static string BuildDraft(string listWikitext, string articleTitle, string indexTitle, DateTime generated) {
        var (body, categories) = ExtractCategories(listWikitext);
        var sb = new StringBuilder();
        sb.Append("__NOINDEX__\n");
        sb.Append(DraftBanner(articleTitle, indexTitle, FormatDate(generated))).Append('\n');
        sb.Append(body.Trim('\n'));
        if (categories.Count > 0) {
            sb.Append("\n\n{{Draft categories|\n");
            foreach (var category in categories) {
                sb.Append(category).Append('\n');
            }
            sb.Append("}}");
        }
        return Normalize(sb.ToString());
    }

    internal static string DraftBanner(string articleTitle, string indexTitle, string date) =>
        "{{ombox|type=notice|text="
        + $"'''Draft list.''' Generated by [[User:Beastie Bot|Beastie Bot]] on {date} for the article [[{articleTitle}]]. "
        + $"[[{indexTitle}|All draft lists]] · Comments: [[User talk:{StripUserPrefix(indexTitle)}]]"
        + "}}";

    // Removes every [[Category:...]] link from the text and returns them in order. A line left empty
    // by the removal is dropped; a line with other text keeps that text.
    internal static (string Body, IReadOnlyList<string> Categories) ExtractCategories(string wikitext) {
        var categories = new List<string>();
        var kept = new List<string>();
        foreach (var line in wikitext.Replace("\r\n", "\n").Split('\n')) {
            var matches = CategoryLink.Matches(line);
            if (matches.Count == 0) {
                kept.Add(line);
                continue;
            }
            foreach (Match match in matches) {
                categories.Add(match.Value);
            }
            var rest = CategoryLink.Replace(line, string.Empty);
            if (rest.Trim().Length > 0) {
                kept.Add(rest);
            }
        }
        return (string.Join('\n', kept), categories);
    }

    // The text as MediaWiki stores it: LF line endings, trailing whitespace trimmed, Unicode NFC.
    // The sha1 of this string is the sha1 the API reports for the saved revision, which is how an
    // unchanged page is recognised without downloading it.
    public static string Normalize(string text) =>
        text.Replace("\r\n", "\n").Replace('\r', '\n').Normalize(NormalizationForm.FormC).TrimEnd();

    public static string Sha1Hex(string normalizedText) =>
        Convert.ToHexString(SHA1.HashData(Encoding.UTF8.GetBytes(normalizedText))).ToLowerInvariant();

    public static int ByteCount(string text) => Encoding.UTF8.GetByteCount(text);

    public static string? FindIucnVersion(string listWikitext) {
        var match = IucnVersion.Match(listWikitext);
        return match.Success ? match.Groups[1].Value : null;
    }

    public static string BuildIndex(
        string indexTitle,
        IReadOnlyList<DraftIndexEntry> posted,
        IReadOnlyList<DraftIndexEntry> tooLarge,
        DateTime generated,
        string? iucnVersion) {

        var iucn = posted.Where(e => e.Group == DraftGroup.Iucn).ToList();
        var australia = posted.Where(e => e.Group == DraftGroup.Australia).ToList();
        var date = FormatDate(generated);
        var version = iucnVersion is null ? "the IUCN Red List" : $"the IUCN Red List (version {iucnVersion})";

        var sb = new StringBuilder();
        sb.Append("__NOINDEX__\n");
        sb.Append($"Draft list articles generated by [[User:Beastie Bot|Beastie Bot]] on {date}: {iucn.Count} lists from {version}, ");
        sb.Append($"and {australia.Count} lists of threatened species of Australia from the EPBC Act Species Profile and Threats Database (SPRAT), the IUCN Red List and the threatened species lists of the Australian states and territories.\n\n");
        sb.Append("Each draft is for the article with the same title. In the \"Article\" column, a blue link means that article exists now; a red link means there is no article with that title yet.\n\n");
        sb.Append($"Comments: [[User talk:{StripUserPrefix(indexTitle)}]]\n");

        AppendTable(sb, $"IUCN Red List ({iucn.Count} lists)", iucn);
        AppendTable(sb, $"Australia ({australia.Count} lists)", australia);

        if (tooLarge.Count > 0) {
            sb.Append("\n== Not posted ==\n");
            sb.Append("These lists are over Wikipedia's 2 MB page size limit:\n");
            foreach (var entry in tooLarge) {
                sb.Append($"* [[{entry.ArticleTitle}]] ({FormatMegabytes(entry.Bytes)})\n");
            }
        }
        return Normalize(sb.ToString());
    }

    private static void AppendTable(StringBuilder sb, string heading, IReadOnlyList<DraftIndexEntry> entries) {
        if (entries.Count == 0) {
            return;
        }
        sb.Append($"\n== {heading} ==\n");
        sb.Append("{| class=\"wikitable sortable\"\n");
        sb.Append("! Draft !! Article !! Size (kB)\n");
        foreach (var entry in entries) {
            sb.Append("|-\n");
            sb.Append($"| [[{entry.DraftTitle}|{entry.ArticleTitle}]] || [[{entry.ArticleTitle}]] || style=\"text-align:right\" | {FormatKilobytes(entry.Bytes)}\n");
        }
        sb.Append("|}\n");
    }

    // Wikipedia reports page sizes in units of 1,000 bytes.
    internal static string FormatKilobytes(int bytes) =>
        Math.Max(1, (int)Math.Round(bytes / 1000.0)).ToString("N0", CultureInfo.InvariantCulture);

    internal static string FormatMegabytes(int bytes) =>
        (bytes / 1_000_000.0).ToString("0.0", CultureInfo.InvariantCulture) + " MB";

    private static string StripUserPrefix(string title) =>
        title.StartsWith("User:", StringComparison.Ordinal) ? title["User:".Length..] : title;
}
